import React from 'react';
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./Footer";
import NewsLetter from "./NewsLeeter";
import QueryWrapper from "./QueryWrapper";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


 

  return (
    <html lang="en">
      <body className={theme === 'light' ? inter.className : 'dark'}>
        <QueryWrapper>
 
          {children}
          <NewsLetter />
          <Footer />
        </QueryWrapper>
      </body>
    </html>
  );
}
